name: Deploy website to S3 bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Configure AWS Credentials with IAM Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: us-east-1

      - name: Set Deployment Environment Variables
        run: |
          echo "AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}" >> $GITHUB_ENV
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
          echo "CLOUDFRONT_DISTRIBUTION_ID=${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" >> $GITHUB_ENV

      - name: Cache Hugo Resources
        uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-hugo-

      - name: Build Website
        run: hugo --minify --cacheDir /tmp/hugo_cache

      - name: Deploy to S3 & Invalidate CloudFront
        run: hugo deploy --maxDeletes -1 --invalidateCDN
